@startuml

title __UTIL's Class Diagram__\n

  package  {
    package com.samsung.tcm {
      package com.samsung.tcm.util {
        class StringSearcher {
            - THRESHOLD : int
            + StringSearcher()
            + contains()
            + startsWith()
            + count()
            - search()
            - search()
            - computeLPSArray()
        }
      }
    }
  }
  

  package  {
    package com.samsung.tcm {
      package com.samsung.tcm.util {
        class TestCaseFileFilter {
            - root : File
            - isInvoked : boolean
            - fileSet : HashSet<File>
            {static} - tcFileFilter : TestCaseFileFilter
            {static} + configure()
            + filterFiles()
            + listTestcaseFiles()
            + generateFilterType()
            - filterOut()
            - filterOut()
            - listFilesWithFilterString()
            - addToFileSetByFilter()
            - isMatch()
            - isDirFiltered()
            - getFileNameWithoutExt()
            - isValidParameter()
        }
      }
    }
  }
  

  package  {
    package com.samsung.tcm {
      package com.samsung.tcm.util {
        class NeedCheck {
            - chkFile : File
            - filterStr : String
            - isInMatchedDir : boolean
            - needCheck : boolean
            - inMatchedDir : boolean
            ~ NeedCheck()
            ~ isNeedCheck()
            ~ isInMatchedDir()
            ~ decide()
        }
      }
    }
  }
  

  package  {
    package com.samsung.tcm {
      package com.samsung.tcm.util {
        class FilterTypeMapper {
            {static} + mapToFilterType()
        }
      }
    }
  }
  

  package  {
    package com.samsung.tcm {
      package com.samsung.tcm.util {
        enum FilterType {
          FILE_EXT
          FILE_NAME_PREFIX
          FILE_NAME_POSTFIX
          FILE_NAME_EXACTLY
          FILE_NAME_ALL
          DIR_NAME_PREFIX
          DIR_NAME_POSTFIX
          DIR_NAME_EXACTLY
          DIR_NAME_ALL
        }
      }
    }
  }
  

  package  {
    package com.samsung.tcm {
      package com.samsung.tcm.util {
        class TestCaseFileRegExprFilter {
            - root : File
            - dirPattern : Pattern
            - filePattern : Pattern
            + TestCaseFileRegExprFilter()
            + listTestcaseFiles()
            + listTestcaseFiles()
            - listFilesWithPattern()
        }
      }
    }
  }
  

  TestCaseFileFilter +-down- NeedCheck
  TestCaseFileFilter +-down- FilterTypeMapper
  TestCaseFileFilter +-down- FilterType
  NeedCheck o-- FilterType : filterType


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
